### ISSUE TITLE
Unable to open channel

### ISSUE THREAD

**Issue by karzak** [interledgerjs/ilp-plugin-xrp-asym-client#18]
I was following the tutorial on using ILP on live net (https://medium.com/interledger-blog/joining-the-live-ilp-network-eab123a73665) and got the following error. 

```
2018-04-16T18:11:22.619Z connector:app error TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at Object.encodeChannelProof (/Users/kjd/.nvm/versions/node/v8.9.4/lib/node_modules/moneyd/node_modules/ilp-plugin-xrp-paychan-shared/lib/util.js:110:12)
    at Plugin._connect (/Users/kjd/.nvm/versions/node/v8.9.4/lib/node_modules/moneyd/node_modules/ilp-plugin-xrp-asym-client/index.js:178:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

My config file looks like this:

```
{
  "secret": "xxxxxxxxxxxxxxx",
  "rippled": "wss://s1.ripple.com",
  "parent": "client.scyl.la"
}
```

**Comment by justmoon** [comment]
This looks like the "not enough money" error. We have added better logging/error messages which will be in the next release.
